LazyManager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),

    path('users/', include('users.urls')),

    path('api/', include('main.api_urls', namespace='main_api')),
    path('api/', include('users.api_urls', namespace='users_api')),

    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),

    path('tasks/', views.tasks, name='tasks'),
    path('tasks/create_task/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/delete/', views.delete_task, name="task_delete"),
    path('tasks/<int:task_id>/toggle/', views.toggle_task_completion, name="task_toggle"),
    path('tasks/<int:task_id>/view/', views.view_task, name="view_task"),
    path('tasks/<int:task_id>/edit/', views.edit_task, name="edit_task"),

    path('search/', views.SearchResults.as_view(), name='search_results'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'users'

urlpatterns = [
    path("logout/", views.logout_view, name="logout"),
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path('profile/clear_avatar', views.clear_avatar, name="clear_avatar"),
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.core.exceptions import ValidationError

from django.utils import timezone

from django.conf import settings


def validate_date(date):
    if date < timezone.now():
        raise ValidationError('Введите возможный дедлайн!')

class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(default='Middle', max_length=50)
    creation_date = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)
    deadline = models.DateTimeField(blank=True, null=True, validators=[validate_date])
    is_overdue = models.BooleanField(default=False)

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.username, filename)

class CustomUser(AbstractUser):
    date_of_birth = models.DateField(null=True, blank=True)
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to=user_directory_path, null=True, blank=True)

    def __str__(self):
        return self.username

main/forms.py
from django.forms import ModelForm
from .models import Task
from django.contrib.auth.models import User

class CreateTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'deadline', 'priority']
        labels = {
            'title': 'Задача',
            'description': 'Описание задачи',
            'deadline' : 'Срок выполнения',
            'priority' : 'Приоритет'
        }



class EditTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'deadline', 'priority']
        labels = {
            'title': 'Задача',
            'description': 'Описание задачи',
            'deadline' : 'Срок выполнения',
            'priority' : 'Приоритет'
        }

main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.authentication import JWTAuthentication

from .permissions import IsOwnerOrAdmin

from .models import Task
from .forms import CreateTaskForm, EditTaskForm

from django.views.generic import ListView
from django.db.models import Q





from rest_framework import generics
from .serializers import TaskSerializer
import django_filters
from rest_framework.filters import OrderingFilter

@login_required
def tasks(request):
    task_list = Task.objects.filter(user=request.user)
    if request.user.is_authenticated:
        return render(request, 'main/tasks.html', {'tasks': task_list})
    else:
        return redirect('users:login')


def homepage(request):
    return render(request, 'main/homepage.html')

@login_required
def create_task(request):
    error = ''
    if request.method == 'POST':
        form = CreateTaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user_id = request.user.id
            task.save()
            return redirect('main:tasks')
        else:
            error = 'Неверно заполнен дедлайн'
    form = CreateTaskForm()
    context = {'form': form, 'error': error}
    return render(request, 'main/create_task.html', context)


@login_required
def edit_task(request, task_id):
    error = ''
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        form = EditTaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('main:tasks')
        else:
            error = 'Неверно заполнен дедлайн'
    form = EditTaskForm(instance=task)
    context = {'form': form, 'task': task, 'error': error}
    return render(request, 'main/edit_task.html', context)


@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.method == "POST":
        task.delete()
        return JsonResponse({"success": True})

    return JsonResponse({"success": False, "error": "Invalid request"}, status=400)


@login_required
def view_task(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    return render(request, 'main/view_task.html', {'task': task})


@login_required
def toggle_task_completion(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.method == "POST":
        task.is_completed = not task.is_completed  # Переключаем состояние
        task.save()
        return JsonResponse({"success": True, "is_completed": task.is_completed})

    return JsonResponse({"success": False, "error": "Invalid request"}, status=400)




class SearchResults(ListView):
    model = Task
    template_name = 'main/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Task.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query) | Q(priority__icontains=query), user=self.request.user
        )
        return object_list



class TaskFilter(django_filters.FilterSet):
    title = django_filters.filters.CharFilter(field_name='title', lookup_expr='icontains')
    description = django_filters.filters.CharFilter(field_name='description', lookup_expr='icontains')
    deadline = django_filters.filters.DateTimeFilter(field_name='deadline', lookup_expr='lte')
    priority = django_filters.filters.CharFilter(field_name='priority', lookup_expr='icontains')
    is_completed = django_filters.filters.BooleanFilter(field_name='is_completed')

    class Meta:
        model = Task
        fields = ['title', 'description', 'deadline', 'priority', 'is_completed']


class TaskListCreateView(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    authentication_classes = [JWTAuthentication]
    permission_classes = [IsAuthenticated, IsOwnerOrAdmin]
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend, OrderingFilter)
    filterset_class = TaskFilter

    ordering_fields = ('title', 'description', 'deadline', 'priority', 'is_completed')

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class TaskDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrAdmin]

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)

templates/main/create_task.html
{% extends 'base.html' %}

{% block title %}Создать задачу{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>Создать новую задачу</h2>
        <form method="post">
            {% csrf_token %}

            <label for="id_title">{{ form.title.label }}</label>
            {{ form.title }}

            <label for="id_description">{{ form.description.label }}</label>
            {{ form.description }}
            <label for="id_deadline">{{ form.deadline.label }}</label>
            <input type="datetime-local" name="deadline" id="id_deadline" required>

            <label for="id_priority">{{ form.priority.label }}</label>
            <select name="priority" id="id_priority">
                <option value="Low">Low</option>
                <option value="Middle">Middle</option>
                <option value="High">High</option>
            </select>

            <button type="submit" class="btn save">Сохранить</button>
        </form>
        {% if error %}
            <div class="form-errors">
                <li>{{ error }}</li>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/main/edit_task.html
{% extends 'base.html' %}

{% block title %}Редактировать задачу{% endblock %}

{% block content %}
    <div class="form-container">
        <h2>Редактировать задачу</h2>
        <form method="post">
            {% csrf_token %}

            <label for="id_title">{{ form.title.label }}</label>
            {{ form.title }}

            <label for="id_description">{{ form.description.label }}</label>
            {{ form.description }}

            <label for="id_deadline">{{ form.deadline.label }}</label>
            <input type="datetime-local" name="deadline" id="id_deadline" value="{{ form.deadline.value|date:'Y-m-d\TH:i' }}" required>
            <label for="id_priority">{{ form.priority.label }}</label>
            <select name="priority" id="id_priority">
                <option value="Low" {% if form.priority.value == "Low" %}selected{% endif %}>Low</option>
                <option value="Middle" {% if form.priority.value == "Middle" %}selected{% endif %}>Middle</option>
                <option value="High" {% if form.priority.value == "High" %}selected{% endif %}>High</option>
            </select>

            <button type="submit" class="btn save">Сохранить</button>
            {% if error %}
            <div class="form-errors">
                <li>{{ error }}</li>
            </div>
            {% endif %}
        </form>

    </div>
{% endblock %}

templates/main/homepage.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Главная страница {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <p>тут будут таблицы, друзья и тд</p>
    {% else%}
        <p>тут будет инфа и предложение зарегаться</p>
    {% endif %}
{% endblock %}

templates/main/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="profile-container">
    <h2>Профиль пользователя</h2>

    <div class="profile-header">
        <div class="avatar">
            {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="Аватар" class="avatar-img">
            {% else %}
                <img src="{% static 'images/default-avatar.png' %}" alt="Аватар" class="avatar-img">
            {% endif %}
        </div>
        <div class="profile-info">
            <p><strong>Имя:</strong> {{ user.first_name }}</p>
            <p><strong>Фамилия:</strong> {{ user.last_name }}</p>
            <p><strong>Юзернейм:</strong> {{ user.username }}</p>
            <p><strong>Дата рождения:</strong> {{ user.date_of_birth|date:"d.m.Y" }}</p>
        </div>
    </div>

    <div class="friends-section">
        <h3>Список друзей</h3>
        <!-- Здесь будет список друзей (будущая фича) -->
        <p>Здесь будет отображаться список ваших друзей.</p>
    </div>

    <div class="edit-profile-section">
        <h3>Редактировать профиль</h3>
        <form method="post" enctype="multipart/form-data" class="profile-edit-form">
            {% csrf_token %}

            <label for="id_first_name">Имя:</label>
            {{ form.first_name }}

            <label for="id_last_name">Фамилия:</label>
            {{ form.last_name }}

            <label for="id_date_of_birth">Дата рождения:</label>
            {{ form.date_of_birth }}

            <label>Фото профиля:</label>
            {% if user.avatar %}
                <div class="avatar-edit-container">
                    <a href="{% url 'users:clear_avatar' %}" class="btn btn-danger">Удалить фото</a>
                </div>
            {% else %}
                <p>Фото профиля не загружено.</p>
            {% endif %}

            <div class="upload-wrapper">
                <label for="id_avatar" class="btn btn-secondary">Загрузить новое фото</label>
                <input type="file" name="avatar" id="id_avatar" class="custom-file-input">
            </div>

            <button type="submit" class="btn btn-success">Сохранить изменения</button>
        </form>
    </div>
</div>
{% endblock %}

templates/main/search_results.html
{% extends 'base.html' %}

{% block title %}Результаты поиска{% endblock %}

{% block content %}
<div class="container">
  <form action="{% url 'main:search_results' %}" class="Search" method="get">
    <input class="Search-box" type="text" id="Search-box" name="q" placeholder="Найти задачу">
    <label class="Search-label" for="Search-box"><i class="fa fa-search"></i></label>
  </form>
</div>

<div class="task-section">
    {% if object_list %}
    <h2>Найденные задачи</h2>
    <ul class="task-list active-tasks">
        {% for task in object_list %}
            <li class="task-card" id="task-{{ task.id }}">
                <div class="task-header">
                    <input type="checkbox" class="task-checkbox" {% if task.is_completed %}checked{% endif %}
                        onclick="toggleTaskCompletion({{ task.id }})">
                    <span class="task-title">{{ task.title }}</span>
                    <span class="task-priority priority-{{ task.priority|lower }}">{{ task.priority }}</span>
                </div>
                <span class="task-deadline">Дедлайн: {{ task.deadline|date:"d.m.Y H:i" }}</span>
                <div class="task-actions">
                    <a href="{% url 'main:view_task' task.id %}" class="task-button view">Посмотреть</a>
                    <a href="{% url 'main:edit_task' task.id %}" class="task-button edit" id="edit-{{ task.id }}">Изменить</a>
                    <a href="#" class="task-button delete" onclick="confirmDelete({{ task.id }})">Удалить</a>
                </div>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <h2>По вашему запросу ничего не найдено.</h2>
    {% endif %}
</div>
<a href="{% url 'main:tasks' %}" class="back-task-button">Назад</a>
{% endblock %}

templates/main/tasks.html
{% extends 'base.html' %}


{% block title %} Мои задачи {% endblock %}

{% block content %}
<div class="container">
  <form action="{% url 'main:search_results' %}" class="Search" method="get">
    <input class="Search-box" type="text" id="Search-box" name="q" placeholder="Найти задачу">
    <label class="Search-label" for="Search-box"><i class="fa fa-search"></i></label>
  </form>
</div>


<div class="task-section">
    <h2>Список задач</h2>
    <ul class="task-list active-tasks">
        {% for task in tasks %}
        {% if not task.is_completed %}
            <li class="task-card" id="task-{{ task.id }}">
                <div class="task-header">
                    <input type="checkbox" class="task-checkbox" {% if task.is_completed %}checked{% endif %}
                        onclick="toggleTaskCompletion({{ task.id }})">
                    <span class="task-title">{{ task.title }}</span>
                    <span class="task-priority priority-{{ task.priority|lower }}">{{ task.priority }}</span>
                </div>
                <span class="task-deadline">Дедлайн: {{ task.deadline|date:"d.m.Y H:i" }}</span>
                {% if task.is_overdue %}
                    <span class="overdue-label">Просрочено</span>
                {% endif %}
                <div class="task-actions">
                    <a href="{% url 'main:view_task' task.id %}" class="task-button view">Посмотреть</a>
                    <a href="{% url 'main:edit_task' task.id %}" class="task-button edit" id="edit-{{ task.id }}">Изменить</a>
                    <a href="#" class="task-button delete" onclick="confirmDelete({{ task.id }})">Удалить</a>
                </div>
            </li>
        {% endif %}
        {% endfor %}
    </ul>
    <a href="{% url 'main:create_task' %}" class="add-task-button">+ Добавить задачу</a>

</div>

<div class="task-section completed-section">
    <h2>Завершенные задачи</h2>
    <ul class="task-list completed-tasks">
        {% for task in tasks %}
            {% if task.is_completed %}
                <li class="task-card completed" id="task-{{ task.id }}">
                    <div class="task-header">
                        <input type="checkbox" class="task-checkbox" checked
                            onclick="toggleTaskCompletion({{ task.id }})">
                        <span class="task-title">{{ task.title }}</span>
                        <span class="task-priority priority-{{ task.priority|lower }}">{{ task.priority }}</span>
                    </div>
                    <span class="task-deadline">Дедлайн: {{ task.deadline|date:"d.m.Y H:i" }}</span>
                    <div class="task-actions">
                        <a href="" class="task-button view">Посмотреть</a>
                        <a href="#" class="task-button delete" onclick="confirmDelete({{ task.id }})">Удалить</a>
                    </div>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

{% endblock %}

templates/main/view_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ task.title }}{% endblock %}

{% block content %}
<div class="task-card">
    <h2 class="task-card-title">{{ task.title }}</h2>

    <div class="task-card-info">
        <span class="badge priority-{{ task.priority|lower }}">
            Приоритет: {{ task.priority }}
        </span>
        <p><strong>Дедлайн:</strong> {{ task.deadline|date:"d.m.Y H:i" }}</p>
        <p><strong>Описание:</strong> {{ task.description }}</p>
        {% if task.is_overdue %}
            <span class="overdue-label">Просрочено</span>
        {% endif %}
    </div>

    <div class="task-card-actions">
        <a href="{% url 'main:tasks' %}" class="btn btn-secondary">Назад</a>
        <a href="{% url 'main:edit_task' task.id %}" class="btn btn-warning">Изменить</a>
        <a href="#" class="btn btn-danger" onclick="confirmDelete({{ task.id }})">Удалить</a>
    </div>
</div>
{% endblock %}